// <auto-generated />
using System;
using BoostEntityFrameworkUygulamaMaraton.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoostEntityFrameworkUygulamaMaraton.DAL.Migrations
{
    [DbContext(typeof(AlbümDbContext))]
    partial class AlbümDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoostEntityFrameworkUygulamaMaraton.ENTITIES.Concrete.Albüm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlbümAdı")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AlbümCikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AlbümFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AlbümIndirimOrani")
                        .HasColumnType("int");

                    b.Property<string>("AlbümSanatciGrup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AlbümSatisDevamliligi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Albümler");
                });

            modelBuilder.Entity("BoostEntityFrameworkUygulamaMaraton.ENTITIES.Concrete.Yonetici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("YoneticiKullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YoneticiSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Yoneticiler");
                });
#pragma warning restore 612, 618
        }
    }
}
